### ISSUE TITLE
Build Submission

### ISSUE THREAD

**Issue by cooldudeachyut** [SethClydesdale/code-vein-builder#10]
Build Name: Comfy Prometheus
Build Category: One-handed Sword
Build Link/Code: https://sethclydesdale.github.io/code-vein-builder/?build=IIVgPsCMkQ7BNgAYwGFEuADjAURejOgMxgBixBAnOQEwAsaOF46AbGrbWiEA
Build Description: Good damaging build maining Jack's sword Executioner, and meant to use 3 buffs: Adrenaline, Bridge to Glory and Blade Dance which don't have any negative effects unlike Sacrificial Edge and Final Journey, or being somewhat conditional like Overdrive if you get hit often.

When all hits connect, Pulsating Light quickly adds up 25% damage bonus on a single usage with Blade Dance active, making it an excellent damage racking tool. Bloodsucking Blades is an awesome support skill to execute the combat skills readily.

Can also add Numbing Mark to a light Stun transformed weapon like Blazing Claw or Iceblood, maintaining quick mobility against bosses that can be stunned for an easier fight, or just add the corresponding elemental weakness weapon buff to the Executioner. However, since this requires player to manage 4 buffs simultaneously, which is obviously not very comfy, the general strategy should be to apply an elemental weapon buff only when Blade Dance runs out, giving it enough time for cooldown for the next usage.

**Comment by SethClydesdale** [comment]
Hello @cooldudeachyut,

Thank you for another submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIVgPsCMkQ7BNgAYwGFEuADjAURejOgMxgBixBAnOQEwAsaOF46AbGrbWiEA&context=IwCwPgwg9gtgZgTwAQAUBOsCmAXEmCuAzkA). If you need to make any edits, feel free to let me know.

Have a good day.
