### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by anidarkk** [SethClydesdale/code-vein-builder#11]
Build Name: Blade Bearer
Build Category: Light Gift/ Dex / Str
Build Link/Code: https://sethclydesdale.github.io/code-vein-builder/?build=IIBgPsAcYMICwQIwQExPVJaaIGxgFFwdoYVkzttEBOWOnYyIA
Build Description: this build is essentially stacking buffs on each other. the bridge to glory being the best of them. if you can avoid being hit, overdrive is also a major buff. tested at +9 (both weapon and blood veil) and with all the buffs active, it does around 2.5k damage per hit with the ice blood.
The Dammerung is there in case something is resistant to ice and the ice buff can be changed for another element if needed.
bloodsucking blades says it cant be used but if you use Cognitive Zeal before, it becomes available due to the increase to willpower and with all the drain upgrades, you can do strong attacks with the ice blood and still regen ichor making it a viable option in a fight without risking the ichor you need back to make sure to keep the buffs up and running.

**Comment by SethClydesdale** [comment]
Hello @anidarkk,

Thank you for the submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIBgPsAcYMICwQIwQExPVJaaIGxgFFwdoYVkzttEBOWOnYyIA&context=DYSw5gFgLg+mIDMoGcA+AhYBDAJgUwAJ08sAnPUoA). If you need to make any edits, feel free to let me know by leaving a comment or opening a new issue.

Have a good day.
