### ISSUE TITLE
Custom Stun Build

### ISSUE THREAD

**Issue by ReignDestroys** [SethClydesdale/code-vein-builder#12]
This build allows you to stun and slow with the Interesting weapons like the Damerung and Iceblood. This weapons aren't the best, but the do give versatility and damage reduction. It also comes with magic so you can space out your enemy if needed. You will do amazing damage with slow, stun ,and swift destruction. It also comes with a Devour night to get ichor up as fast as possible. Comes with One Handed mastery for ultimate damage. Can be used for bosses but switch out the stun, slow, and magic spells to the right weaknesses of the boss. Here is the Code for the build 
IIBgPsAcYMICwXDAjLAzBBwBMTkDYwBRcKWAdlgFZ0MYBOCbaYZVFMAMWziA

**Comment by SethClydesdale** [comment]
Hello @ReignDestroys,

Thank you for the build submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIBgPsAcYMICwXDAjLAzBBwBMTkDYwBRcKWAdlgFZ0MYBOCbaYZVFMAMWziA&context=CYUwRgrgZlA+DKB3AllALgAnmiA7XIATkA). If you want to make any edits to it, just let me know!

Have a good day.
