### ISSUE TITLE
法系配装——极致吸血

### ISSUE THREAD

**Issue by YoumuMoe** [SethClydesdale/code-vein-builder#14]
Build Name: 极致吸血
Build Category: Dark Gift
Build Link/Code: IIZgHAPgwgjCEAYICEBsFgCZEe8GekSxOJUmM0m2SAogKxA
Build Description: 一个可以拉满自身吸血能力的配装，在此配装下推图可以达到一刀7冥血的吸血效率，在boss战时，这个数值可以翻倍，极限之歌可以增加自身50%的法术伤害和吸血，由于吸血能力也进行了强化，极限之歌下的法术消耗增加将会被抵消，且冥血会更为充足。绝对零度铠可以提供高额的防御和伤害。该配装也是法系配装最为通用的。空出来的技能可根据地图特性以及自身偏好进行携带

**Comment by YoumuMoe** [comment]
Build Name: drain Extreme
Build Category: Dark Gift
Build Link/Code: IIZgHAPgwgjCEAYICEBsFgCZEe8GekSxOJUmM0m2SAogKxA
Build Description: This build can increase your drain rating to 6.0. In this build, you can drain 7 ichor while playing and drain 21 ichor by one hit in boss battle.Ephemeral Refrain can increase your drain and by 50% and higher than the  2 ichor usage.Ymir and Subzero Shroud can provide high damage and defence.You can select skills for the stage and the battle into the empty blank.

**Comment by SethClydesdale** [comment]
Hello @YoumuMoe,

Thank you for the submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIZgHAPgwgjCEAYICEBsFgCZEe8GekSxOJUmM0m2SAogKxA&context=CYQwTg1g+g5glgMwC4GcA+hA80C+BgOFUAIRQA). If you need to make any edits, feel free to let me know by leaving a comment or opening a new issue.

Have a good day.
