### ISSUE TITLE
Build Submission: Raijin, God of Lightning

### ISSUE THREAD

**Issue by dmkellison** [SethClydesdale/code-vein-builder#17]
Build Name: Raijin, God of Lightning
Build Category: dark gifts
Build Link/Code: https://sethclydesdale.github.io/code-vein-builder/?build=IIFgDAPsBsGQIgRiiOVnEQJggYQJwQCikuiyAYiABxQCsswWGWquWOBezEFAzNCA
Build Description: This Build is highly based around lightning and fast cooldowns and high damage, you should always buff up before entering a fight, then you can just use all of your abilities as much as you want because they do high damage and are very cheap so you can always have a lot of ichor thanks to you drain buffs and as long as the enemy isn't immune to lughtning then they should go down pretty fast, even if they are resistant!

**Comment by SethClydesdale** [comment]
Hello @dmkellison,

Thank you for the submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIFgDAPsBsGQIgRiiOVnEQJggYQJwQCikuiyAYiABxQCsswWGWquWOBezEFAzNCA&context=CYQwTg1g+g5glgMwC4GcA+AlEcBWcB2ANAAQDiA9sMeQsQDJwwAWS+BMQA). If you need to make any edits, feel free to let me know by leaving a comment or opening a new issue.

Have a good day!
