### ISSUE TITLE
New build

### ISSUE THREAD

**Issue by DarkWarrior7534** [SethClydesdale/code-vein-builder#18]
**Build Name:** Blademaster (Comfort One-handed Sword)
**Build Category:** One-Handed Sword
**Build Link/Code:** IIBgPsDMECwQjApxEGEBsYCi5UE4xV5Ms4AxAJgrEvMl0miMIA5C8g
**Build Description:** Your basic one-handed sword non-dlc build. Good to use if you are heading into the DLC's.

**Comment by SethClydesdale** [comment]
Hello @DarkWarrior7534,

Thank you for the submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIBgPsDMECwQjApxEGEBsYCi5UE4xV5Ms4AxAJgrEvMl0miMIA5C8g&context=IwCwPgQgNghgJgUwLYwM4BcECcg). If you need to make any edits, feel free to let me know by leaving a comment or opening a new issue.

Have a good day!
