### ISSUE TITLE
Vali Halbert Build

### ISSUE THREAD

**Issue by Powaifu** [SethClydesdale/code-vein-builder#19]
Build Name: Dancing Scythe 
Build Category: Halbert
Build Code: IIFgDAPgwgrBwEYCc0Bs9KI-AHBAogEzQIIQBiCAzBYSuSPDOlIXK2VCq461UA
Build Description: 
This build is for those who enjoy a good sparring with bosses rather than attempt to one-shot everything. 
Black Halbert has great move set, but Impaler also works as it has two consecutive piercing strikes and is highly effective in staggering enemies e.g. the Cerberus Troopers. Fulmen Blade Fortified is basically a shield as it has 100 defense all around, especially effective against Gilded Hunter's angry phase and the Virgin Born's massive lightning barrage (you know what I'm talking about). 
Chariot Rush has a rather long casting time, but it can be canceled halfway. Switch for Severing Abyss or other offensive skills to suit your playstyle. Thunderbolt impact is a great light AOE when surrounded by mobs, but consider switching between this and Cloak of Winter to match enemies' elemental weakness (There is no Blood/Fire counterparts sadly). It also deals crush damage which the Halbert class completely lacks. I don't recommend this during boss fights, but it is more than enough during exploring as it can one-shot basic mobs (euphoric soldiers, dogs, monkeys and alike) even in max difficulty using this setup. I personally find them annoying especially when surrounded by them so I always bring this with me, but you can switch to modest offering during boss fights to keep your partner alive or elemental damage buffs if you play solo. 
Special notes: In the city of falling flame, switch out Gift Accelerator and Hasten for Flame protection and Elemental wall for maximum fire resistance; plus I personally find being quick mobility in this area can sometimes be a hinderance as I constantly dash into the wall, but normal rolls are much more manageable.

**Comment by SethClydesdale** [comment]
Hello @Powaifu,

Thank you for the submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIFgDAPgwgrBwEYCc0Bs9KI-AHBAogEzQIIQBiCAzBYSuSPDOlIXK2VCq461UA&context=BYQwNgRgpgTgJgHwCIgHYGMCWqDmACAZXQE8AXYKIA). If you need to make any edits, feel free to let me know by leaving a comment or opening a new issue.

Have a good day!
