### ISSUE TITLE
Build Submission: infinite dodge

### ISSUE THREAD

**Issue by velox-mortem** [SethClydesdale/code-vein-builder#21]
Build Name: infinite dodge
Build Category: bayonet
Build Link/Code: https://sethclydesdale.github.io/code-vein-builder/?build=IIFgjAPgomkwTBAIgNgsRH2YJzrAAzJh5JgAcEAwvJTXjYgGICsRZds18aUBQA
Build Description: "All stats up", increases all stats by one TIER, when you are focused, so you can use your stamina skills.

**Comment by SethClydesdale** [comment]
Hello @velox-mortem,

Thank you for the submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIFgjAPgomkwTBAIgNgsRH2YJzrAAzJh5JgAcEAwvJTXjYgGICsRZds18aUBQA&context=EYQwng9gdgpgLgHwJJQGYEsrrjABAEQgBMBzGIA). If you need to make any edits, feel free to let me know by leaving a comment or opening a new issue.

Have a good day!

**Comment by velox-mortem** [comment]
Sorry, I overlooked something. The gift "Morale Boost" isn't usable in that build, even with the "All stats up" passive. I would like to to replace it with "Time Crunch".

**Comment by SethClydesdale** [comment]
No problem, it should now be updated! ([new link](https://sethclydesdale.github.io/code-vein-builder/?build=IIFgjAPgomkwTBAIgNgsRH2YJzrAAzJh5JgAcEAwvJVQMxE2IBiArEWXbNfGlASA&context=EYQwng9gdgpgLgHwJJQGYEsrrjABAEQgBMBzGIA))
