### ISSUE TITLE
Queen's Polka

### ISSUE THREAD

**Issue by Powaifu** [SethClydesdale/code-vein-builder#22]
Build Name: Queen's Polka
Build Category: Bayonet 
Build Code:IIJgHAPgognBAMFgDYkgUgLNbxIGEBGQpQ1AMRAsPSJKMXxAFYJzsnsoBmIA
Build Description: 
**Why would a Queen sully her status and hands by melee? Bring along your little servant Mia (or White Mia) and start dancing to the sound of your enemies dying from afar.** 
If you don't have DLC use Ivory Grace Devour since it has the 2nd highest drain rating of all blood veils. In that case, you don't have to use Hasten and are free to use whatever support gift or buff you see fit. If you have to melee, use drain attacks and backstab as much as you can. 
The build should be pretty self-explanatory, the main DPS is Fusillade Rondo and you can melt most enemies (not boss) in the game with one burst. It also serves as an "AOE" since you can switch target during casting, enabling you to take down up to 4 enemies per burst. Though this is a bossing setup, you can switch out Gift Accelerator passive for Life Steal during exploration. Oh and get good with dodging. Queen doesn't get hit :p

**Comment by SethClydesdale** [comment]
Hello @Powaifu,

Thank you for the submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIJgHAPgognBAMFgDYkgUgLNbxIGEBGQpQ1AMRAsPSJKMXxAFYJzsnsoBmIA&context=EYQwng9gdgpgLgHwIoFcYygcgM4AIAKEANgNYhA)!

Have a good day!
