### ISSUE TITLE
Build Submission: Bridge to Tranquility

### ISSUE THREAD

**Issue by velox-mortem** [SethClydesdale/code-vein-builder#23]
Build Name: Bridge to Tranquility
Build Category: One-handed Sword, Two-handed Sword
Build Link/Code: https://sethclydesdale.github.io/code-vein-builder/?build=IIFgDAPsCM0QQtATBAInYKZSwTitJOvugBwQDCS5F0N+AYiHGZYZUgGwQCiYQA
Build Description: The damage of "Tranquil Slice" scales with the mind/willpower stat of your weapon, as well as the mind/willpower stat of your Bloodcode. If you want to go for a pure one-hit Build, you could/should use "Ranged Impact" as well (as it also affects the damage).

**Comment by SethClydesdale** [comment]
Hello @velox-mortem,

Thank you for the submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIFgDAPsCM0QQtATBAInYKZSwTitJOvugBwQDCS5F0N+AYiHGZYZUgGwQCiYQA&context=IwCwPgQgTglgJgcwKYAIAuB7FAVKBDAOwEcBXGAGxjQE8g)!

Have a good day!
