### ISSUE TITLE
Build Submission: Flexible Tanker

### ISSUE THREAD

**Issue by sivvy4402** [SethClydesdale/code-vein-builder#24]
Build Name: Flexible Tanker
Build Category: Two-handed Sword
Build Link/Code: https://sethclydesdale.github.io/code-vein-builder/?build=IIJgnAPgQgbBAMEDCjgEYEXRAohqiScSAHBAGIgDsEAIgKzIiLkDMIyG5ALE5KUA
Build Description: Just tank your way around enemies with amazing weapon range, when heavily surrounded use Cleansing Light and Tripple Annihilator. It's a hybrid build of strength with dex.

**Comment by SethClydesdale** [comment]
Hello @sivvy4402,

Thank you for the submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIJgnAPgQgbBAMEDCjgEYEXRAohqiScSAHBAGIgDsEAIgKzIiLkDMIyG5ALE5KUA&context=EwCwPgYgNgpgHgSwEawAQBUCGA7A1jAJyA). If you need to make any edits, feel free to let me know by leaving a comment or opening a new issue.

Have a good day!
