### ISSUE TITLE
Demeter Halberd Build

### ISSUE THREAD

**Issue by sivvy4402** [SethClydesdale/code-vein-builder#25]
Build Name: Hybrid Battle Mage
Build Category: Halberd
Build Link/Code: https://sethclydesdale.github.io/code-vein-builder/?build=IIZgDAPgwgLBnAIwWHByCiAmaA2FAnCojgGJZFRbJRGlxIjHJJklA
Build Description: Close melee build based on light gifts along with good weapon attack.

**Comment by SethClydesdale** [comment]
Hello @sivvy4402,

Thank you for the submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIZgDAPgwgLBnAIwWHByCiAmaA2FAnCojgGJZFRbJRGlxIjHJJklA&context=BYQwNgRgpgTgJgHwBIE8IwJZwAQCEQAuBYU2AsiAOZRA)!

Have a good day!
