### ISSUE TITLE
code vein hp mania mod

### ISSUE THREAD

**Issue by luckysexyqueen** [SethClydesdale/code-vein-builder#26]
Build Name: code vein hp mania
Build Category: player Character
Build Link/Code: https://sethclydesdale.github.io/code-vein-builder/?build=IIZg7APgDBBCCsEDCJkEZqeB4MBiALBHhgKJHYwAiATBijRFfWo7W-EA
Build Description:make to korean Translation please.

**Comment by SethClydesdale** [comment]
Hello @luckysexyqueen,

Thank you for the submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIZg7APgDBBCCsEDCJkEZqeB4MBiALBHhgKJHYwAiATBijRFfWo7W-EA&context=EwCwPgEgCgBAsgQwHYEsFA). If you need to make any edits, feel free to let me know by leaving a comment or opening a new issue.

In regards to a Korean translation, I am unfortunately not fluent in the language, thus the only solution would be a machine translation which is not favorable. Anyone, however, is free to create and submit a translation. For more information about translating, please see the following page.
https://sethclydesdale.github.io/code-vein-builder/translate/

If any questions, do let me know!
