### ISSUE TITLE
코드베인 나만의 모드

### ISSUE THREAD

**Issue by luckysexyqueen** [SethClydesdale/code-vein-builder#27]
Build Name: 
Build Category: 
Build Link/Code:https://sethclydesdale.github.io/code-vein-builder/?build=IIZg7APsCsEEIAYIGERQIwa8JxMDEAWCfADggBEAmTVKyq+-dc4KtfKpfEb9ATiA 
Build Description: 
![캡처](https://user-images.githubusercontent.com/84852627/120671322-3c5c8180-c4cc-11eb-8f61-b22df87c3fca.PNG)

**Comment by SethClydesdale** [comment]
Hello @luckysexyqueen,

Is this an update for #26 or a new build?

If a new build, please provide a name. 
```
Build Name: REQUIRED
```

Thank you
