### ISSUE TITLE
Build Submission: Gwynevere's Flame 

### ISSUE THREAD

**Issue by StuCat215** [SethClydesdale/code-vein-builder#28]
Build Name: Gwynevere's Flame 
Build Category: Dark Gifts
Build Link/Code: IIRgLAPsDsECKTiKzQqgDigTggYVz1mAGYAmfEAVggDEAGFGvZPMitrOM+oA
Build Description: Dark Mage Hybrid

**Comment by SethClydesdale** [comment]
Hello @StuCat215,

Thank you for the submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIRgLAPsDsECKTiKzQqgDigTggYVz1mAGYAmfEAVggDEAGFGvZPMitrOM+oA&context=CYQwTg1g+g5glgMwC4GcA+BxA7gTwHYCmAbgWAQOQoAEAYgDYgC2BQA). If you need to make any edits, feel free to let me know by leaving a comment or opening a new issue.
