### ISSUE TITLE
Build Submission

### ISSUE THREAD

**Issue by MCCLM001** [SethClydesdale/code-vein-builder#29]
Build Name: Bayonet One-Shot
Build Category: Bayonet
Build Link/Code: https://sethclydesdale.github.io/code-vein-builder/?build=IIBgPgognG7AbGYBGWTUGEDsSAckAWJGAMQFZwNkBmME5AJjCqKsutqtQgKA
Build Description: This build is a more reliable one shot, and in some cases is actually more effective than the traditional halberd one shot build. You can do the standard trick of swapping between mind and strength passives to use bridge to glory in addition to everything else, but in a lot of cases it is unnecessary, especially since the standard build uses Ruinous Chevalier instead of Noble Silver or Ivory Grace due to the higher stat scaling. feel free to run this the same way you would a standard halberd one-shot build if you want to, I'm sure it'll be just as effective. And here's the original video showing off the build: www.youtube.com/watch?v=kWUAD54IfVM&t=0s

**Comment by SethClydesdale** [comment]
Hello @MCCLM001,

Thank you for the submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIBgPgognG7AbGYBGWTUGEDsSAckAWJGAMQFZwNkBmME5AJjCqKsutqtQgKA&context=EYQwng9gdgpgLgHwELmvABAeVgWgMoAWEcQA). If you need to make any edits, feel free to let me know by leaving a comment or opening a new issue.
