### ISSUE TITLE
Display total weight with each weapon, and mobility with each weapon

### ISSUE THREAD

**Issue by kkahmed** [SethClydesdale/code-vein-builder#3]
Sorry if I missed something about this or if I'm not using the builder correctly, but do you plan to have the builder show the total weight and therefore mobility? Damage is difficult to do, especially because the final effect of transformations is quite complicated/it's hard to discern the exact calculation.

But for weight it should be straightforward:

- Fort increases by 10%. Alleviate decreases by 20%

- Revenant's Ambition increases the code's base weight limit by 30%

- Being below 50% weight limit or 20% weight limit ups you by 1 or 2 mobility tiers. Being above 100% weight limit or 135% weight limit downs you by 1 or 2 mobility tiers. 

Hope this makes sense, thanks!

**Comment by SethClydesdale** [comment]
Hi @kkahmed,

At the moment the total weight and mobility level aren't implemented. It is something I have on my todo list to possibly add in the future though. As you already figured out, some things aren't included such as HP and Damage due to the lack of mathematical formulas. The data you provided for the weight/mobility should prove useful when I'm ready to work on those implementations however.

This is how mobility is classified right now. (only in use for base mobility, which is static)
- 0 = slow
- 1 = normal
- 2 = quick

If I understood correctly, at or below 20% weight would be quick, 50% normal, and 100% slow, yes?

**Comment by kkahmed** [comment]
> If I understood correctly, at or below 20% weight would be quick, 50% normal, and 100% slow, yes?

Sort of, but not quite. What you said is true for codes with initial mobility of Slow.

e.g. Atlas is 250 base weight, and initial class is Slow. That means 125 is the line between Normal/Slow, and 50 is the line between Quick/Normal. If you use Revenant's Ambition, it becomes 250*1.3=325 base. That means 162.5 is the line between Normal/Slow, 65 is the line between Quick/Normal. 

But it's different for others. Ishtar is 100 base weight, and initial class is Normal. That means 100 is the line between Normal/Slow, and 50 is the line between Quick/Normal. If you use Revenant's Ambition, it becomes 100*1.3=130 base. That means 130 is the line between Normal/Slow, 65 is the line between Quick/Normal.

Scout is 60 base weight, and initial class is Quick. That means 81 is the line between Normal/Slow, and 60 is the line between Quick/Normal. If you use Revenant's Ambition, it becomes 60*1.3=78 base. That means 105.3 is the line between Normal/Slow, 78 is the line between Quick/Normal.

What I don't know off the top of my head is if the comparison check is < and > or if it's <= and >=. Would have to look into what happens when your weight is exactly on the boundary.

Hope that helps!

**Comment by SethClydesdale** [comment]
Thanks, that makes a lot more sense. So, the base mobility seems to adjust the thresholds for slow, normal, and quick. Something like this?

- Base: Slow = 250/2 (normal/slow), 250/5 (quick/normal)
- Base: Normal = 100 (normal/slow), 100/2 (quick/normal)
- Base: Quick = 60*1.35 (normal/slow), 60 (quick/normal)

If that's the case, the last hurdle will just be setting up the ranges, but it shouldn't be too hard. Going by what you said, something like this should suffice. (using atlas as an example)
`weight > 250/2 ? 'slow' : weight <= 250/2 && weight > 250/5 ? 'normal' : 'quick'`

**Comment by kkahmed** [comment]
Quick clarification - I just noticed that while Alleviation is the same for weapons and veils (-20% to their weight), Fortification is different. It is indeed a 10% increase in veil weight, but it's a 15% increase for weapon weight. 

Also the rounding on the boundary is... confusing. I would need to try to do more extensive testing, but it seems to not be consistent. With Scout carrying exactly 60/60 weight, I was bumped down to slow. But with Ishtar carrying exactly 50/100 weight, I remained Quick. 

¯\_(ツ)_/¯

**Comment by SethClydesdale** [comment]
Thanks for the info, it helps a lot! I'll probably start taking a crack at this sometime after I'm finished adding in the preset system.

**Comment by SethClydesdale** [comment]
So far I've gotten the weight functionality down on pre-production. Last order of business is to implement the comparisons in the equipment and blood code selection.

For calculating the mobility, this is the current formula. (taking into account what you mentioned for Scout/Ishtar)
```javascript
switch (base) { // base mobility
  case 0 : // slow
    return weight > max / 2 ? _lang.mobi.slow : weight <= max / 2 && weight > max / 5 ? _lang.mobi.normal : _lang.mobi.quick;

  case 1 : // normal
    return weight >= max ? _lang.mobi.slow : weight < max && weight > max / 2 ? _lang.mobi.normal : _lang.mobi.quick;

  case 2 : // quick
    return weight > max * 1.35 ? _lang.mobi.slow : weight <= max * 1.35 && weight >= max ? _lang.mobi.normal : _lang.mobi.quick;
}
```
I performed some additional tests on blood codes in-game to try and fine tune it and so far it seems to be true to how mobility is calculated in-game. Here's to hoping there isn't any anomalies lol.

Gonna tackle the last of it tomorrow and hopefully will have it online by then or the weekend.

**Comment by SethClydesdale** [comment]
Weight and Mobility should now be live! Let me know if you spot any bugs or inaccuracies.

**Comment by kkahmed** [comment]
Hadn't been able to play the game for a little while, but I just started it up this weekend and tried a few combinations. So far so good, thanks for the functionality!

**Comment by SethClydesdale** [comment]
No problem, great to hear it's working proper! I encountered a few bugs a little after sending it online, but they're all cleaned up now (thankfully).

**Comment by kkahmed** [comment]
Hi @SethClydesdale I think the logic for the weight boundaries got updated in some patch XD

Scout appears to stay quick at exactly 60/60 now, so it seems the update was a buff to the player making it easier to stay at high mobility.

**Comment by SethClydesdale** [comment]
Ah, that's good to hear! Thanks for giving me the heads up. I'll look into tweaking the logic sometime tomorrow to make sure it reflects that.

**Comment by SethClydesdale** [comment]
The builder [should now be updated](https://github.com/SethClydesdale/code-vein-builder/commit/47ba22c66ade91d50596a400d0d3c27dc484e994) with the new weight requirements. 

Normal was also changed, so at 100%/100% weight with a Normal base mobility blood code, your mobility will be Normal instead of Slow. Slow base mobility blood codes appear to be unchanged, so it looks like it was a buff to Normal and Quick base mobility codes.
