### ISSUE TITLE
Build Submission: Unbreakable Bastion

### ISSUE THREAD

**Issue by Blade-of-Want** [SethClydesdale/code-vein-builder#30]
**Build Name:** Unbreakable Bastion
**Build Category:** Halberd
**Build Link/Code:** https://sethclydesdale.github.io/code-vein-builder/?build=IIRgrAPgwiEAwQCKwQ0FQCZolgMXxAGYlM0AOabRAFgj0wE57868wg
**Build Description:** This is a support build that takes advantage of the Bardiche's great blocking without totally sacrificing damage and mobility. For maximum tanking, using a Guard Booster in tandem with Steady Bulwark will negate all chip damage.

**Comment by SethClydesdale** [comment]
Hello @Blade-of-Want,

Thank you for the submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIRgrAPgwiEAwQCKwQ0FQCZolgMXxAGYlM0AOabRAFgj0wE57868wg&context=BYQwNgRgpgTgJgHwKoDsIyiA1iCYoAEAQiAM4AuAlgPYpA). If you need to make any edits, feel free to let me know by leaving a comment or opening a new issue.

**Comment by Blade-of-Want** [comment]
Hi, I'd like my build to be edited. Could you please add the Fortification transformation on the Bardiche? Thanks in advance.

**Comment by SethClydesdale** [comment]
Hi @Blade-of-Want! Your build should now be updated. Here's the [new link](https://sethclydesdale.github.io/code-vein-builder/?build=IIRgrAPgwiEAwQCK1PCrQCZolgMXxAGYlMFgAOabRAFgj0wE4H968wg&context=BYQwNgRgpgTgJgHwKoDsIyiA1iCYoAEAQiAM4AuAlgPYpA).

**Comment by Blade-of-Want** [comment]
Hello again, I would like this build to be deleted, since I'll be posting its replacement soon. When I do so, should I open a new issue or post the new build here?

**Comment by SethClydesdale** [comment]
Hi! Since it's a new build, feel free to open a new issue for it.
