### ISSUE TITLE
CV Build Submission

### ISSUE THREAD

**Issue by Spell2260** [SethClydesdale/code-vein-builder#31]
Build Name: Frost Gattler
Build Category: Bayonet
Build Link/Code: IIFgjAPgomnAbBAIo4cQTRAwrHBmTADmgwDEBWABhz231QoCYIywXsmOmNOwg
Build Description: Build is centered around using Bloody Snow's charged heavy to quickly gattle down medium/big enemies. Both drain skills + an Argent Wold Blade Devour ensures u wont run out of ichor, Ranged Impact to buff your charged heavy, Ichor Efficiency when u run into bosses and will need more than a couple of attacks to take them down, Frost Turret for some extra stopping/stagger power, Radiant Barrel for pesky enemies u dont wanna give a chance to move or to open a boss fight on ranges you otherwise wouldnt be a able to hit from, Gift Extension for obvious reasons, and to top it all off Blood Sacrifice for if there are no enemies nearby to drain from, or if you dont wanna risk getting close and personal.

**Comment by SethClydesdale** [comment]
Hello @Spell2260,

Thank you for the submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIFgjAPgomnAbBAIo4cQTRAwrHBmTADmgwDEBWABhz231QoCYIywXsmOmNOwg&context=EYQwng9gdgpgLgHwGICcIGc4AIDiI5wA2MKQA). If you need to make any edits, feel free to let me know by leaving a comment or opening a new issue.
