### ISSUE TITLE
Build Submission: Unbreakable Bastion 2.0

### ISSUE THREAD

**Issue by Blade-of-Want** [SethClydesdale/code-vein-builder#33]
It's ready. Don't forget to delete the old build please.

**Build Name:** Unbreakable Bastion 2.0
**Build Category:** Halberd
**Build Link/Code:** https://sethclydesdale.github.io/code-vein-builder/?build=IIVgPgwgjGAMYBEbBvFYUCZJRgMXygGZEoAWDKATh0Qr0xoU3gLDxCA
**Build Description:** This is a well-balanced, defence-oriented build that combines Steady Bulwark with the fortified Bardiche for zero chip damage. Royal Heart should be used to prevent enemy combos or to finish off weak enemies. The Ivory Grace is chosen for its extremely high drain rating. Crimson Moon’s high damage, high casting speed and wide area-of-effect make it ideal for close-quarters combat.

**Comment by SethClydesdale** [comment]
Hello @Blade-of-Want, your build should now be online [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIVgPgwgjGAMYBEbBvFYUCZJRgMXygGZEoAWDKATh0Qr0xoU3gLDxCA&context=BYQwNgRgpgTgJgHwKoDsIyiA1iCYoAEAQiAM4AuAlgPYoEBMAdAAxA)! (this has replaced the previous build)

As always, if you need to make any updates to it, do let me know.
