### ISSUE TITLE
Build Submission: "Too Slow"

### ISSUE THREAD

**Issue by Yodel-Daddy** [SethClydesdale/code-vein-builder#34]
Build Name: "Too Slow"
Build Category: One-Handed Sword
Build Link/Code: https://sethclydesdale.github.io/code-vein-builder/?build=IIJgLAPgDBwBwQEIFZq0qCBhAjDYOGCAojAGJgIU4QUDMtYMWIAnI+y1Xa0A
Build Description: Utilizes a bunch of stamina-related active Gifts for a neverending assault. Although damage is relatively low, it offers excellent mobility for a pure hack'n'slash action. 

Active Gifts:
- A combination of "Valiant Heart", "Morale Boost" and "Invigorating Rush" greatly enhances your stamina and is a core of this build, so they should be active at all times. 
- Both "Serene Stance" and "Focus Recovery" serve as an emergency stamina restoration.
- "Lightning Charge" and "Savage Dive" allow you to be even more mobile and cover long distances in no time.
- "Tranquil Slice" for a burst of damage whenever you need it.

Passive Gifts:
- "Swift Destruction" and "One-Handed Sword Mastery" are self-explanatory.
- "Dexterity/Fortitude Up" is used to gain access to "Invigorating Rush", "Serene Stance" (both require Fortitude S) and "Focus Recovery" (requires Dexterity S).
- "Vow of Ichor" allows you to be a bit more aggressive with active Gifts, but it is not necessary and can be replaced with any passive Gift of your choice (my personal recommendation would be either "Increased Gift Speed" or "Stamina Stimulant")

Since there's no place for "Blood Sacrifice" or the like, rocking a "Devour" sword is a must. If used as intended, this build eats Ichor like no tomorrow.

Additional note: The idea behind using Heimdall is that you can swap either "Lightning Charge" or "Savage Dive" for "Sacrificial Edge" on the fly. Basically, sacrifice some of your mobility options for X2 damage if you feel like the fight is taking too long. Think of it as your personal "Second Stage" buff.

**Comment by SethClydesdale** [comment]
Hello @Yodel-Daddy,

Thank you for the submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIJgLAPgDBwBwQEIFZq0qCBhAjDYOGCAojAGJgIU4QUDMtYMWIAnI+y1Xa0A&context=IwCwPgKg9lAEDKAbKB3IA). If you need to make any edits, feel free to let me know by leaving a comment or opening a new issue.
