### ISSUE TITLE
Build Submission: Ahead Flank

### ISSUE THREAD

**Issue by Blade-of-Want** [SethClydesdale/code-vein-builder#35]
Hello again. Could you please let me know if there's a build limit per user? I wouldn't want to get carried away posting all my stupid ideas.

**Build Name:** Ahead Flank
**Build Category:** One-handed Sword
**Build Link/Code:** https://sethclydesdale.github.io/code-vein-builder/?build=IIJgLAPsAMGwIgRis2xnAJwpBAwosgGKIDM+I2oke5BA7BEeBEpPCLCUA
**Build Description:** Named after the emergency speed of my beloved Cyclops from Subnautica, this is an all-out build that demands proper resource management and rewards unceasing offense. Blast Bolt is chosen for its high damage, long range and high ichor efficiency, with the latter being especially critical for Heimdall. Morale Boost increases Heimdall's sky-high stamina to absurd levels and pairs beautifully with Tirelessness. Survival Instinct is paired with Feral Tenacity to safely boost damage at low HP.

**Comment by SethClydesdale** [comment]
Hello @Blade-of-Want!

There is currently no build limit; you're free to submit however many builds you like. Your current submission should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIJgLAPsAMGwIgRis2xnAJwpBAwosgGKIDM+I2oke5BA7BEeBEpPCLCUA&context=IwCwPggiCmCGAmACAYgG1gOwNZA). As always, if you need to make any changes, don't hesitate to let me know!
