### ISSUE TITLE
Build Submission: The Freischuetz

### ISSUE THREAD

**Issue by CloudStriker94** [SethClydesdale/code-vein-builder#36]
**Build Name:** The Freischuetz
**Build Category:** Bayonet
**Build Link/Code:** https://sethclydesdale.github.io/code-vein-builder/?build=IIRgrAPgogDNBMFQTqpIkA5oBYIGEQMAxeANiQuIGY4bJ9498BOCYuQkIA
**Build Description:** A bayonet build that focuses on mobility and aggression without sacrificing the ability to take the occasional hit, dealing good damage both at range and up close, and able to stagger even most bosses with repeated shots from the Riot Breaker. You can slot in different buffs and even a variety of damaging gifts without much trouble.

**Comment by SethClydesdale** [comment]
Hello @CloudStriker94 ,

Thank you for the submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIRgrAPgogDNBMFQTqpIkA5oBYIGEQMAxeANiQuIGY4bJ9498BOCYuQkIA&context=EYQwng9gdgpgLgHwCoAsYAIBiAnGBLAZwGMUBXeALyA). If you need to make any edits, feel free to let me know by leaving a comment or opening a new issue.

**Comment by CloudStriker94** [comment]
Update: IIRgrAPgogTNCcFRLstIkA5oBYIGEQMAxGANgJjmIGYAGCWyfGPfRYhwkIA
Description and name can stay the same.

**Comment by SethClydesdale** [comment]
Hello @CloudStriker94, your build should now be updated! ([new link](https://sethclydesdale.github.io/code-vein-builder/?build=IIRgrAPgogTBoAZ4nnYAWZy0A5qYGEQUCYBmCUuAMTKVslMIE4JqkiQg&context=EYQwng9gdgpgLgHwCoAsYAIBiAnGBLAZwGMUBXeALyA))

**Comment by CloudStriker94** [comment]
Aye, looking good. Thanks!
________________________________
