### ISSUE TITLE
Build Submission: Kings Glory

### ISSUE THREAD

**Issue by mrdoodleduck** [SethClydesdale/code-vein-builder#39]
**Build Name:** Kings Glory
**Build Category:** One-handed Sword
**Build Link/Code:** https://sethclydesdale.github.io/code-vein-builder/?build=IIBgPsBsbgIgjGAwo8xHABwQEzhYgKLgBiALGCfDpThSTgMzLZICcyArMo40A
**Build Description:** A One-handed build with damage and movement in mind. The stun ability with the Argent Wolf Blade is very useful when fighting bosses who have various attacks when stunned granting you an extra 4-5 seconds to unleash a bombardment of attacks before the enemy has a chance to charge/activate abilities. The Ivory Grace with the Fortification ability grants you a balance of speed, defense, and durability paired with the Cleansing Light gift makes you spend less regeneration items allowing you to progress the current area you're in more. If used correctly this Build should take you through the entire story with ease including all of the depths not including the ones listed in the disclaimer below.

**Disclaimer:** This build is NOT recommended for the following areas:
Depths: Fiery Oblivion [ DLC ]
Depths: Celestial Ice Prison [ DLC ]
Depths: Eternal Abyss [ DLC ]
Depths: Tower Of Trials 2 & 3

**Comment by SethClydesdale** [comment]
Hello @mrdoodleduck,

Thank you for the submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIBgPsBsbgIgjGAwo8xHABwQEzhYgKLgBiALGCfDpThSTgMzLZICcyArMo40A&context=IwCwPg0glgdg5gZwAQHEA2B7ATgTyA). If you need to make any edits, feel free to let me know by leaving a comment or opening a new issue.
