### ISSUE TITLE
Fleeting Edge(One-Handed Sword Build) Submission

### ISSUE THREAD

**Issue by KaeTheDandere** [SethClydesdale/code-vein-builder#41]
Build Name: Fleeting Edge
Build Category: One-Handed Sword
Build Link/Code: IIJg7APsAsWcAGKJlSQMQIwGYIGFMVgAOCAUQxFnRFywixTxFII1jwE4g
Build Description: I made this build primarily due to my desire to go fast. Requires none of the DLC 

General 

• Scout is my Blood Code of choice, as it's relatively the same to Queenslayer, but has slightly more ichor and Dexterity, as well as allowing quick Mobility with my weapons of choice. 

• Dawn Claw is my Blood Veil of choice, as it is a pretty good veil for due to it's drain rating and stats as well as fashion, you may choose another similar to it if you want. Make sure to Alleviate it in order to gain quick mobility on your weapon 

• Enduring Crimson and Blazing Edge are both very good weapons and are what I use. Enduring Crimson and Blazing Claw have Intensification on it to make the scaling into dex higher, and so that you can do more damage. You may choose any other One-handed sword if you want, just make sure it can reach quick mobility.

Active Skills 

• Phantom Assault is good for getting in close to the enemy as it has a decent amount if range. Deals a decent amount of damage as well 

• Circating Pulse is usually used when the boss is staggered, recovering from their attack, or after using Phantom Assault. Good amount of damage. 

• Blood Sacrifice is needed due to the buffs that are used, it helps in gaining ichor without the use of items. 

• Sympathetic Boon is there as I primarily use this in coop to revive or heal the host. If you aren't doing coop you can replace it with any buff like Adrenaline, or a damage dealing gift like Shadow Assault. 

• Overdrive is a good buff for this build as you'll probably end up doing your best to not get hit. It specifically gives you a 25% attack buff for 90 seconds, but will end if you get hit. However you may replace it with Bloodsucking Blades for higher drain by removing Tirelessness and replacing it with any Willpower up passives if you desire. 

• Bridge to Glory is one of the best buffs in the game I believe. It scales with the Mind stat and can do over 2x normal damage, lasts a decent amount of time as well at 90 seconds. 

• Valiant Heart is a buff that I like to use at it reduces the stamina consumption of dodges by 40%, and you're gonna be dodging a lot. 

• Cleansing Light is a good gift to use just in case you actually get hit as it recovers 75% of the damage that was dealt to you. 

Passive skills 

• Tirelessness is a great passive skill as it increases your stamina regeneration rate by 33.3%, can be replaced with willpower up passives if you want Bloodsucking Blades for an Active Gift 

• Mind/Vitality up is needed in order to use Bridge to Glory, without it you'll be left to choose a different, weaker attack buff. 

• Swift Destruction increases the damage you deal in proportion to your mobility, and because we have quick mobility already you will get a 20% increase. 

• One-Handed Sword Mastery is needed if you eant to be able to do more damage with a One-Handed Sword by 20%

**Comment by SethClydesdale** [comment]
Hello @KaeTheDandere,

Thank you for the submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIJg7APsAsWcAGKJlSQMQIwGYIGFMVgAOCAUQxFnRFywixTxFII1jwE4g&context=IwCwPgYgNgpjAuBLAdgcwAQFEAmqZA). If you need to make any edits, feel free to let me know by leaving a comment or opening a new issue.
