### ISSUE TITLE
I'm terrible at names!

### ISSUE THREAD

**Issue by saliathings** [SethClydesdale/code-vein-builder#42]
**Build Name:** Gift Spam (For DLC Bosses)
**Build Category:** One-handed
**Build Link/Code:** https://sethclydesdale.github.io/code-vein-builder/?build=IIJhB9gDnAGcAiBGOr4FF4GEkWQdnCwDYiBWcAMQBYrciRasBOREbJbMIA
**Build Description:** I was having trouble getting Eva and Mia's costumes and started playing around with builds to see what worked. This is the result. Works with any companion or solo. Minimal dodging required.

It's a one-handed sword build for use against the DLC bosses. The basic idea is to safely (or at least as safely as possible) spam the gifts of the Iceblood (against Lord of Thunder) and Blazing Claw (against Frozen Empress) weapons to do a lot of mindless damage. Doesn't work as well with Fulmen Blade but you can swap in Lightning Weapon and whack at it with Executioner/Enduring Crimson (against Hellfire Knight).

You can probably swap in the active skills Time Crunch (if you prefer to charge the strong attack rather than tap it) or Serene Stance. Speed can be Quick or Normal, though I prefer Quick. Can swap most of the passive gifts if you prefer other Blood Veils or want to boost attack. Tirelessness works well.

Works with Artemis and most other Blood Codes. Can replace Bridge with most other attack boosting gifts or Venom Mark.

1. Cleansing Light
2. Feral Tenacity
3. Gift Extension
4. Overdrive
5. Bloodsucking Blades
6. Bridge to Glory
7. Numbing Mark

Blood Sacrifice as needed.

**Comment by SethClydesdale** [comment]
Hello @saliathings,

Thank you for the submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIJhB9gDnAGcAiBGOr4FF4GEkWQdnCwDYiBWcAMQBYrciRasBOREbJbMIA&context=IwCwPg4glgZgLgAgMoAcCGBbBAKAYgewCcEARAGQGEEAhfAZzoFM6BKIA). If you need to make any edits, feel free to let me know by leaving a comment or opening a new issue.
