### ISSUE TITLE
Build Submission [by Sentaired1]

### ISSUE THREAD

**Issue by SentaiRed1** [SethClydesdale/code-vein-builder#43]
Build Name: Church of Zwei
Build Category: Two Handed Weapons
Build Link/Code: https://sethclydesdale.github.io/code-vein-builder/?build=IIZgjAPgQpAMHEoi9kFFIGEwBYEE5p4AxEQ0vbeAEXjUsMwA4JMQBWIA / IIZgjAPgQpAMHEoi9kFFIGEwBYEE5p4AxEQ0vbeAEXjUsMwA4JMQBWIA
Build Description: Utilizes a Zwiehander to tear through everyone

**Comment by SethClydesdale** [comment]
Hello @SentaiRed1,

Thank you for the submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIZgjAPgQpAMHEoi9kFFIGEwBYEE5p4AxEQ0vbeAEXjUsMwA4JMQBWIA&context=EwCwPgwiCuBODGIAEB7AZkgWgdwKYEsg). If you need to make any edits, feel free to let me know by leaving a comment or opening a new issue.
