### ISSUE TITLE
Effective build

### ISSUE THREAD

**Issue by kanekifan** [SethClydesdale/code-vein-builder#44]
**Build Name:** one shot
**Build Category:** queen slayer
**Build Link/Code:** IIBgPgogHGwOywKywEyvcGEAsYDCCeAjAMz5FHm7FrFkBiRa92yO+JJQA
**Build Description:** I created the build its effective towards story bosses but not against Mido is difficult to counter

My discord is ichgofan

**Comment by SethClydesdale** [comment]
Hello @kanekifan,

Thank you for the submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIBgPgogHGwOywKywEyvcGEAsYDCCeAjAMz5FHm7FrFkBiRa92yO+JJQA&context=EYQwng9gdgpgLgHwPKwAQGUAWE5A). If you need to make any edits, feel free to let me know by leaving a comment or opening a new issue.
