### ISSUE TITLE
Build Submission: Jolly cooperation

### ISSUE THREAD

**Issue by Parapuch** [SethClydesdale/code-vein-builder#48]
Build Name: Jolly cooperation
Build Category: Light gifts, guarding
Build Link/Code: https://sethclydesdale.github.io/code-vein-builder/?build=IIZgDAPsBMUKwQEIigRjRgYrT7GwFFJtYBhADglIE4IARAFgkwV2djtRCA
Build Description: Support build fit to assisting other players. Sacrifices mobility to boasts high defences, 100% physical guard and high balance. Empowers regeneration and features advanced health sharing. Attack boosting gifts provide long lasting bonus. Tip: for some bosses, vanishing hollow can be proficient to avoid aoe explosion attacks.

**Comment by SethClydesdale** [comment]
Hello @Parapuch,

Thank you for the submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIZgDAPsBMUKwQEIigRjRgYrT7GwFFJtYBhADglIE4IARAFgkwV2djtRCA&context=DYSw5gFgLg+mIDMoGcA+ApA9sYBPABAMKaYAOApgE4CGUImAdkA). If you need to make any edits, feel free to let me know by leaving a comment or opening a new issue.
