### ISSUE TITLE
Build Submission Knight of Ishtar

### ISSUE THREAD

**Issue by calypsoup** [SethClydesdale/code-vein-builder#5]
**Build Name:** Knight of Ishtar
**Build Category:** One handed Sword, Overdrive Build
**Build Link/Code:** IIZgjAPsCcWc8QQAxVQUVcAHHATHAGwQBiIArKXgCxVJmoDCujeSjsjYyQA
**Additional Comments (optional):** 
In certain situations one of the skills can be swapped for elemental damage or Gift Speed passive for Stamina,Health steal etc, build is very fast and depends on how good you are dodging but can kill anything Don't use spacebar to dodge with this build, your dodge is Swifting Hallow, ALWAYS keep your stamina for swings, cleared ng+6 with this, Increased Gift Speed will help you execute skills way faster and greatly redurce your risk of getting hit while using a skill

**Comment by SethClydesdale** [comment]
Hello @calypsoup,

Thanks for the build submission! Your build should now be available in the preset list. 👍

I never realized gift speed affected skill-based (weapon) Gifts. Definitely gonna give this build a try later when I hop on. Nice stuff!
