### ISSUE TITLE
code vein assassin halberd bd

### ISSUE THREAD

**Issue by SilvrWill** [SethClydesdale/code-vein-builder#52]
Build Name: Assassin Halberd
Build Category: Halberd
Build Link/Code: https://sethclydesdale.github.io/code-vein-builder/?build=IIJg7APgwgrNAsEAiBGCp1oAzoBzRRwFEQCBmCAMRUksUpAE4r59rSpmoREpCg&lang=zh-hant&
Build Description: It's a build for halberd users use to explore the map. Night Fog Veil can make sure you can hit the enemy first, most of enemy will get stun at first two hit then you can combo them to dead. With the high poise enemy, you can start with backstab, then finish them with Chariot Rush high damage. This build not good to boss fight but it can let you have a comfortable experience .

**Comment by SethClydesdale** [comment]
Hello @SilvrWill,

Thank you for the submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIJg7APgwgrNAsEAiBGCp1oAzoBzRRwFEQCBmCAMRUksUpAE4r59rSpmoREpCg&context=BYQwNgRgpgTgJgHwIIGcUjQSwHYAIAS408QA). If you need to make any edits, feel free to let me know by leaving a comment or opening a new issue.
