### ISSUE TITLE
Submission: Perfectly Balanced Prometheus

### ISSUE THREAD

**Issue by taz4s** [SethClydesdale/code-vein-builder#54]
Build Name: Perfectly balanced Prometheus
Build Category: One-handed Sword
Build Link/Code: IIVgPsCMkQHGARGwBMFkGY5gKIAYwAxANnTUIBYZCUKiNTKwBheZlGZyAr4oA
Build Description: The goal of the build is to take tools from prometheus blood code and make the best use out of it. Since blood code from itself doesn't have the best stats, the idea is to use weapons with 4 scaling stats as well as the buff only prometheus can use: Blade dance. Playstyle: Fast attacks that gets buffed when you hit enemies many times in quick succession as well as dodging their attacks with quick mobility.

**Comment by SethClydesdale** [comment]
Hello @taz4s,

Thank you for the submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIVgPsCMkQHGARGwBMFkGY5gKIAYwAxANnTUIBYZCUKiNTKwBheZlGZyAr4oA&context=IwCwPgCgpgTgZlAxgFwDYE8AEAhAhq3AO0SgBNMIYB7AWymRCgFcBnIA). If you need to make any edits, feel free to let me know by leaving a comment or opening a new issue.
