### ISSUE TITLE
Build Submission

### ISSUE THREAD

**Issue by cooldudeachyut** [SethClydesdale/code-vein-builder#9]
Build Name: Dark Fighter
Build Category: Dark Gifts
Build Link/Code: https://sethclydesdale.github.io/code-vein-builder/?build=IIRgTAPgoiHAbBAIrUcAsdUA4IGEBOLIvEVVSUI4AZgFYIAxTR8JmgBnzKA
Build Description: Just a simple build using Artemis and with ability to have strong dark gifts, bayonet usage and cqc with one handed sword. A jack of all trades!

**Comment by SethClydesdale** [comment]
Hello @cooldudeachyut,

Thank you for the submission! Your build should now be available [here](https://sethclydesdale.github.io/code-vein-builder/?build=IIRgTAPgoiHAbBAIrUcAsdUA4IGEBOLIvEVVSUI4AZgFYIAxTR8JmgBnzKA&context=CYQwTg1g+g5glgMwC4GcA+ARcEAEAxOGACyQFMwg). If you need to make any edits, feel free to let me know by leaving a comment or opening a new issue.

Have a good day.

**Comment by cooldudeachyut** [comment]
I updated the 'Dark Fighter' build: https://sethclydesdale.github.io/code-vein-builder/?build=IIRgTAPgognBwHYIBETzcALPSwAcEAwiAMzQAMRIaAYiZcGAyHI2oXMRiUoWGEA

**Comment by SethClydesdale** [comment]
Thanks for letting me know, it should now be updated on Code Vein Builder.
